### ISSUE TITLE
Hamburger Menu Dysfunction in PymPay Repository

### ISSUE THREAD

**Issue by Soumojitshome2023** [AdityaSeth777/PymPay#12]
## Problem:
The hamburger menu in the PymPay repository is not functioning as expected, impacting the navigation experience for users.

## Expected Behavior:
The hamburger menu should toggle and display the navigation options seamlessly, providing an intuitive and user-friendly navigation experience.

## Steps to Reproduce:
1. Open the PymPay repository.
2. Access the website or application.
3. Attempt to open the hamburger menu.

## Current Behavior:
The hamburger menu does not respond or display the navigation options as intended, hindering users from accessing crucial features.

## Screenshot:

![image](https://github.com/AdityaSeth777/PymPay/assets/121761154/497e220d-76a2-4747-8c1d-221f1c3413ed)

**Comment by Soumojitshome2023** [comment]
Please @AdityaSeth777 assign me this issue. I want to work on it. Thank You

**Comment by AdityaSeth777** [comment]
Sure. For the record, this is how an issue should be presented with. I'm assigning it to you. Start working. All the best.

**Comment by AdityaSeth777** [comment]
@Soumojitshome2023 Submit the PR once you are done. Thank you for raising this issue though.
