### ISSUE TITLE
Search Engine Optimisation

### ISSUE THREAD

**Issue by arghadipmanna101** [AdityaSeth777/PymPay#15]
- Search Engine Optimisation and performance enhancement.

![image](https://github.com/AdityaSeth777/PymPay/assets/130065095/c70c3c51-a282-4f4f-8cf5-505c116cdea1)

**Comment by arghadipmanna101** [comment]
please assign me in this work

**Comment by AdityaSeth777** [comment]
Greetings and Thank you for submitting the issue ! This message is automated, in case you are wondering. I will get back to you on this.

**Comment by AdityaSeth777** [comment]
Assigned under Apertre '24. All the best. @arghadipmanna101

**Comment by AdityaSeth777** [comment]
#16 Done. Thank you.
