### ISSUE TITLE
text alignment in "learn more" button and other buttons as well has to be fixed

### ISSUE THREAD

**Issue by deepbeatz** [AdityaSeth777/PymPay#7]
@AdityaSeth777 assign me this issue under aperture24

**Comment by AdityaSeth777** [comment]
Can you please elaborate on the issue ? And provide a valid SS indicating which parts you want to fix. 

Thank you.

**Comment by deepbeatz** [comment]
<img width="960" alt="Screenshot 2024-01-05 022540" src="https://github.com/AdityaSeth777/PymPay/assets/79015311/0dd5b693-4a56-4cfd-852d-9a3f2f97d58a">

**Comment by deepbeatz** [comment]
learn more button not in center in y-axis

**Comment by AdityaSeth777** [comment]
Alright. Assigning.

**Comment by AdityaSeth777** [comment]
Assigned @deepbeatz under Apertre '24 Open Source Program.

**Comment by deepbeatz** [comment]
👌

**Comment by deepbeatz** [comment]
pr is submitted #8

**Comment by AdityaSeth777** [comment]
PR merged. Thanks for contributing !
